language: php
php:
  - 7.1

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE `ofcetest`;'
  - php bin/console migrations:reset

script:
  - vendor/bin/phpstan analyse app -c phpstan.neon  -l 7
  - vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp app

after_script: