language: php
php:
  - 7.2

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

before_script:
  - cp tests/tests.neon app/config/config.local.neon
  - mysql -u root -e 'CREATE DATABASE `ofcetest`;'
  - php bin/console migrations:reset

script:
  - vendor/bin/phpstan analyse app -c phpstan.neon  -l 7
  - vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp app
  - php vendor/nette/tester/src/tester.php -p php -C tests/ --coverage coverage.xml --coverage-src app/model

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config tests/.coveralls.yml